[package]
name = "region_cache_memory_engine"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[features]
testexport = []

[dependencies]
bytes = "1.0"
collections = { workspace = true }
crossbeam = "0.8"
dashmap = "5.1"
engine_rocks = { workspace = true }
engine_traits = { workspace = true }
fail = "0.5"
futures = { version = "0.3", features = ["compat"] }
hex = "0.4"
keys = { workspace = true }
kvproto = { workspace = true }
lazy_static = "1.4.0"
log_wrappers = { workspace = true }
parking_lot = "0.12"
pd_client = { workspace = true }
prometheus = { version = "0.13", default-features = false, features = ["nightly"] }
prometheus-static-metric = "0.5"
security = { workspace = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
skiplist-rs = { git = "https://github.com/tikv/skiplist-rs.git", branch = "main" }
slog = { workspace = true }
slog-global = { workspace = true }
tikv_util = { workspace = true }
txn_types = { workspace = true }
yatp = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
test_pd = { workspace = true }
test_pd_client = { workspace = true }
