[package]
name = "hybrid_engine"
version = "0.0.1"
edition = "2021"
publish = false

[features]
testexport = []

[dependencies]
engine_rocks = { workspace = true }
engine_traits = { workspace = true }
tikv_util = { workspace = true }
txn_types = { workspace = true }

[dev-dependencies]
engine_rocks = { workspace = true }
region_cache_memory_engine = { workspace = true }
tempfile = "3.0"
