[package]
name = "hybrid_engine"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[features]
testexport = []
failpoints = ["fail/failpoints"]

[[test]]
name = "failpoints"
path = "tests/failpoints/mod.rs"
required-features = ["failpoints"]

[dependencies]
crossbeam = { workspace = true }
engine_rocks = { workspace = true }
engine_traits = { workspace = true }
fail = "0.5"
kvproto = { workspace = true }
lazy_static = "1.4.0"
online_config = { workspace = true }
prometheus = { version = "0.13", default-features = false, features = ["nightly"] }
prometheus-static-metric = "0.5"
raft = { workspace = true }
raftstore = { workspace = true }
range_cache_memory_engine = { workspace = true }
slog = { workspace = true }
slog-global = { workspace = true }
tempfile = "3.0"
tikv_util = { workspace = true }
txn_types = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
