name: Pull Request CI

on:
  # push:
  #   branches:
  #     - 'raftstore-proxy*'
  pull_request:
    branches:
      - 'raftstore-proxy*'

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: cache cargo env
        id: cache-cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/rust-toolchain') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: install rust
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain none -y
          export PATH=~/.cargo/bin/:$PATH
          rustup self update && rustup set profile minimal && rustup default $(cat "rust-toolchain")
          # cargo install sccache
      - name: cache build target
        uses: actions/cache@v2
        env:
          cache-name: cargo-target
        with:
          path: |
            target/
            # ~/.cache/sccache/
          key: ${{ runner.os }}-${{ env.cache-name }}-v1-${{ hashFiles('**/rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-v1-${{ hashFiles('**/rust-toolchain') }}-
      - name: format check
        run: |
          cd ${{github.workspace}}
          make gen_proxy_ffi
          [[ -z $(git status -s) ]]
          cargo fmt -- --check >/dev/null
      - name: test
        run: |
          # export RUSTC_WRAPPER=~/.cargo/bin/sccache
          # make test
          # make debug
          cargo check
          cargo test --package tests --test failpoints cases::test_normal
          cargo test --package tests --test failpoints cases::test_bootstrap
          cargo test --package tests --test failpoints cases::test_compact_log
          cargo test --package tests --test failpoints cases::test_early_apply
          cargo test --package tests --test failpoints cases::test_encryption
          cargo test --package tests --test failpoints cases::test_pd_client
          cargo test --package tests --test failpoints cases::test_pending_peers
          cargo test --package tests --test failpoints cases::test_transaction
          cargo test --package tests --test failpoints cases::test_cmd_epoch_checker
          cargo test --package tests --test failpoints cases::test_disk_full
          cargo test --package tests --test failpoints cases::test_stale_peer
          cargo test --package tests --test failpoints cases::test_import_service
          cargo test --package tests --test failpoints cases::test_split_region

          cargo test --package tests --test integrations raftstore::test_bootstrap
          cargo test --package tests --test integrations raftstore::test_clear_stale_data
          cargo test --package tests --test integrations raftstore::test_compact_after_delete
          cargo test --package tests --test integrations raftstore::test_compact_log
          cargo test --package tests --test integrations raftstore::test_conf_change
          cargo test --package tests --test integrations raftstore::test_early_apply
          cargo test --package tests --test integrations raftstore::test_hibernate
          cargo test --package tests --test integrations raftstore::test_joint_consensus
          cargo test --package tests --test integrations raftstore::test_replica_read
          cargo test --package tests --test integrations raftstore::test_snap
          cargo test --package tests --test integrations raftstore::test_split_region
          cargo test --package tests --test integrations raftstore::test_stale_peer
          cargo test --package tests --test integrations raftstore::test_status_command
          cargo test --package tests --test integrations raftstore::test_prevote
          cargo test --package tests --test integrations raftstore::test_region_change_observer
          cargo test --package tests --test integrations raftstore::test_region_heartbeat
          cargo test --package tests --test integrations raftstore::test_region_info_accessor
          cargo test --package tests --test integrations raftstore::test_transfer_leader
          cargo test --package tests --test integrations raftstore::test_single::test_node_apply_no_op
          cargo test --package tests --test integrations raftstore::test_single::test_node_delete




