name: Pull Request CI

on:
  # push:
  #   branches:
  #     - 'raftstore-proxy*'
  pull_request:
    branches:
      - 'raftstore-proxy*'

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: cache cargo env
        id: cache-cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/rust-toolchain') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: install rust
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain none -y
          export PATH=~/.cargo/bin/:$PATH
          rustup self update && rustup set profile minimal && rustup default $(cat "rust-toolchain")
          # cargo install sccache
      - name: cache build target
        uses: actions/cache@v2
        env:
          cache-name: cargo-target
        with:
          path: |
            target/
            # ~/.cache/sccache/
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/rust-toolchain') }}-
      - name: format check
        run: |
          cd ${{github.workspace}}
          make gen_proxy_ffi
          [[ -z $(git status -s) ]]
          cargo fmt -- --check >/dev/null
      - name: test
        run: |
          # export RUSTC_WRAPPER=~/.cargo/bin/sccache
          # make test
          # make debug
          cargo check
          cargo test --package tests --test failpoints -- cases::test_normal --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_bootstrap --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_compact_log --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_early_apply --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_encryption --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_pd_client --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_pending_peers --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_transaction --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_cmd_epoch_checker --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_disk_full --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_snap --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_merge --exact --nocapture
          cargo test --package tests --test failpoints -- cases::test_stale_peer --exact --nocapture
